// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/b/:slug": {
    params: {
      "slug": string;
    };
  };
  "/b/:slug/confirmation/:publicId": {
    params: {
      "slug": string;
      "publicId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/b/:slug" | "/b/:slug/confirmation/:publicId";
  };
  "routes/b.$slug.tsx": {
    id: "routes/b.$slug";
    page: "/b/:slug" | "/b/:slug/confirmation/:publicId";
  };
  "routes/b.$slug.confirmation.$publicId.tsx": {
    id: "routes/b.$slug.confirmation.$publicId";
    page: "/b/:slug/confirmation/:publicId";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/b.$slug": typeof import("./app/routes/b.$slug.tsx");
  "routes/b.$slug.confirmation.$publicId": typeof import("./app/routes/b.$slug.confirmation.$publicId.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
};